name: Deploy Multi-Container App
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_ID }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t ulandj/docker-react -f ./client/Dockerfile.dev ./client
      - run: docker run -e CI=true ulandj/docker-react npm test

      - run: docker build -t ulandj/multi-client ./client
      - run: docker build -t ulandj/multi-nginx ./nginx
      - run: docker build -t ulandj/multi-server ./server
      - run: docker build -t ulandj/multi-worker ./worker

      - run: docker push ulandj/multi-client
      - run: docker push ulandj/multi-nginx
      - run: docker push ulandj/multi-server
      - run: docker push ulandj/multi-worker

#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'
#
#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
#          application_name: multi-docker
#          environment_name: Multidocker-env
#          existing_bucket_name: elasticbeanstalk-eu-west-2-787753257926
#          region: eu-west-2
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
